# This file is generated by the SpeeDNS release workflow. Do not edit.
cask "speedns" do
  version "0.1.0-alpha.6"

  on_macos do
    on_intel do
      sha256 "d0e51d650f3685900a9139311352f81a8482708abc1dfb20f5b615b4cdd99c28"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "a54605fcba38622d58dcd3b6340f7e14e0b4665a82cfd62131a8565bcb9ec12d"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "9fe5db94ade6f36c7d1a5b93946fbea6c4981680bde2bd114c552e6a66dca032"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "87a4c2eb977a20d664490bcb583225524a846bb4686fb144415ef52624818bc8"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  name "speedns"
  desc "Cross-platform DNS transport speed test CLI"
  homepage "https://github.com/crypt0rr/SpeeDNS"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speedns"

end
