# This file is generated by the SpeeDNS release workflow. Do not edit.
cask "speedns" do
  version "0.1.0-alpha.8"

  on_macos do
    on_intel do
      sha256 "2df135959a7f999b3e99f471921c18a5c9b26865d62001e85145f99e44b88963"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "f99732b7150f3393015a1290d32b0efb94a5575ecf3b024013ee1b98b86441aa"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "bdebb4fadde87cecf1b9c5af49108ab20799b89e2eaf81685ce2561c3cc3c43a"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "9d858bd5648241ae507e08ae65484580b3e3e51d6b99a9e3aab075ff2a5bb527"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  name "speedns"
  desc "Cross-platform DNS transport speed test CLI"
  homepage "https://github.com/crypt0rr/SpeeDNS"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speedns"

end
