# This file is generated by the SpeeDNS release workflow. Do not edit.
cask "speedns" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "90f9213191654eefbdaa27bd035847c2fe898e6d1c86a66ab75c8fb18bf7f62a"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "221aed4500a670eb6b9318ecf779c4b25316feabed16c983bbb5c560fb4cd45e"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef28b371d3e3b5315a5b54272a934227349c812d91241ba0528cc389913122b1"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
    on_arm do
      sha256 "4b10fb5d15c910227a528b4dca10ced9abceeb01dd208255bb79b7e69914be56"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crypt0rr/SpeeDNS/releases/download"
    end
  end

  name "speedns"
  desc "Cross-platform DNS transport speed test CLI"
  homepage "https://github.com/crypt0rr/SpeeDNS"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speedns"

end
