# This file was generated by GoReleaser. DO NOT EDIT.
cask "speedns" do
  version "0.1.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "017f0b8e295eb78e0c8b6c6087e872b4ad7a744666f8edf53bac918aa74dac02"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/crypt0rr/dns-speedtest/releases/download"
    end
    on_arm do
      sha256 "e51a1aa1678b5c268991e091954952d7e472af7a1638d9e6f4b34d125d2295f4"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/crypt0rr/dns-speedtest/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "9557101526c8e7e20747649aff49d2ac2120b5c4bcf99f65d5617b5442d88a69"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_amd64.tar.gz",
        verified: "github.com/crypt0rr/dns-speedtest/releases/download"
    end
    on_arm do
      sha256 "426a4f5e8963d51866650c5a2fc2ce3753ee4126efe943ea2127e88aad8ea318"
      url "https://github.com/crypt0rr/SpeeDNS/releases/download/v#{version}/SpeeDNS_#{version}_linux_arm64.tar.gz",
        verified: "github.com/crypt0rr/dns-speedtest/releases/download"
    end
  end

  name "speedns"
  desc "Cross-platform DNS transport speed test CLI"
  homepage "https://github.com/crypt0rr/dns-speedtest"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "speedns"

  # No zap stanza required

end
